// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63R35NYfC1IZtHDFq4xb3B6R7ZAK5-JM',
    appId: '1:991564407410:web:2c5bd2c4ecae8d505f58eb',
    messagingSenderId: '991564407410',
    projectId: 'food-hackss',
    authDomain: 'food-hackss.firebaseapp.com',
    storageBucket: 'food-hackss.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Ehrc245Hz9JHxsgoAFOO8U7k-0C9-0M',
    appId: '1:991564407410:android:f26182484b7613db5f58eb',
    messagingSenderId: '991564407410',
    projectId: 'food-hackss',
    storageBucket: 'food-hackss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdScrVd-ZboV41GJqANeu2NvFLVsY1C98',
    appId: '1:991564407410:ios:184ea41088cba9925f58eb',
    messagingSenderId: '991564407410',
    projectId: 'food-hackss',
    storageBucket: 'food-hackss.appspot.com',
    iosBundleId: 'com.example.foodHacks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdScrVd-ZboV41GJqANeu2NvFLVsY1C98',
    appId: '1:991564407410:ios:a1ebc061f14300e35f58eb',
    messagingSenderId: '991564407410',
    projectId: 'food-hackss',
    storageBucket: 'food-hackss.appspot.com',
    iosBundleId: 'com.example.foodHacks.RunnerTests',
  );
}
